dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
- osx
addons:
  apt:
    packages:
      - flex
      - bison
      - make
      - libboost-all-dev
      - libgsl-dev
      - ghc
  homebrew:
    packages:
      - flex
      - bison
      - make
      - boost
      - gsl
      - ghc
    update: true
install:
  - ./configure
  - make
  - sudo make install
before_script:
  # install missing ghc/haskell modules
  - sudo apt-get install cabal-install -y
  - cabal update
  - cabal install random
  # obtain truth data from secondary github repository
  - git clone https://github.com/jlab/gapc-test-suite.git /home/travis/gapc-test-suite
script:
  - make test-unit
  - make test-paral
  - if [ $TRAVIS_OS_NAME = osx ]; then make test-mod TRUTH_DIR=/home/travis/gapc-test-suite/Truth TRUTH_SUFFIX=_osx; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then make test-mod TRUTH_DIR=/home/travis/gapc-test-suite/Truth TRUTH_SUFFIX=_ubuntu; fi
  - make test-regress TRUTH_DIR=/home/travis/gapc-test-suite/Truth
  - make test-ambiguity TRUTH_DIR=/home/travis/gapc-test-suite/Truth
