dist: xenial
os: linux
language: cpp
compiler:
  - gcc

jobs:
  include:
    - os: linux
      dist: bionic # 18.04
    - os: linux
      dist: xenial # 16.04
    # earlier distributions are lacking libgsl-dev AND are no longer supported by Ubuntu

addons:
  apt:
    packages:
      - flex
      - bison
      - make
      - libboost-all-dev
      - libgsl-dev
      - ghc
      - python3
      - python3-pip

install:
  - ./configure
  - make
  - sudo make install
before_script:
  # install missing ghc/haskell modules
  - sudo apt-get install cabal-install -y
  - cabal update
  - cabal install random
  # obtain truth data from secondary github repository
  - git clone https://github.com/jlab/gapc-test-suite.git /home/travis/gapc-test-suite
  # install c++ linter
  - pip3 install cpplint
script:
  # c++ code style checks
  #- cpplint src/* rtlib/*
  # manually compiling an example to check for raised warnings ...
  - cp testdata/grammar/elm.gap . && gapc -p "buyer * pretty2" elm.gap && make -f out.mf 2>&1 > /dev/null | tee make.stderr
  # ... and test if "warning: dynamic exception specifications are deprecated" are no longer triggered
  - test $(grep "warning:.dynamic exception specifications are deprecated" make.stderr -c) -eq 0
  # run compiler test suite
  - make test-unit
  - make test-paral
  - make test-mod TRUTH_DIR=/home/travis/gapc-test-suite/Truth TRUTH_SUFFIX=_ubuntu
  - make test-regress TRUTH_DIR=/home/travis/gapc-test-suite/Truth
  - make test-ambiguity TRUTH_DIR=/home/travis/gapc-test-suite/Truth
